### ISSUE TITLE
installation does not work...

### ISSUE THREAD

**Issue by TaktischerSpeck** [ZeroByter/zeropanelv2#10]
Hey 

i am trying to install the webinterface but i cant login.

he also does not create any tabel or database but i gave him root rights.

i am using an VPS with plesk and php 7

any suggestions?

**Comment by ZeroByter** [comment]
As far as I know, the web-interface only works with Apache due to it's dependency upon the `.htaccess` file.

**Comment by ZeroByter** [comment]
Bug fixed! Original issue thread [here.](https://github.com/ZeroByter/zeropanelv2/issues/9)
