### ISSUE TITLE
Money Function does not work

### ISSUE THREAD

**Issue by TaktischerSpeck** [ZeroByter/zeropanelv2#11]
Hey :)

i am sorry its me again.

But i cant add or remove money from bank or cash

does anyone else has this probelm?

**Comment by ZeroByter** [comment]
Most likely a database mismatch?? As in, your database stores money under column 'cashMoney' but the panel is trying to modify 'cash'??

**Comment by steveflorim** [comment]
It's Working for me but it doesnt add to the Money Log.

**Comment by ZeroByter** [comment]
Perhaps either:

1. The money logs database wasn't created.
2. There is a bug inside the MySQL statement to create new moneylogs.

I just looked at the code and there doesn't seem to be a problem with either points **1** and **2**, if your up to it @steveflorim I might have to take a closer look at your panel.

**Comment by hadasch1** [comment]
I'm getting this Error if i add or remove money:
`Recoverable fatal error: Object of class stdClass could not be converted to string in C:\xampp\htdocs\phpscripts\requests\changemoneycash.php on line 13`

**Comment by TaktischerSpeck** [comment]
the vars in the db are cash and bankacc

**Comment by ZeroByter** [comment]
@hadasch1 @TaktischerSpeck @steveflorim  There isn't much I can do over GitHub, I'll have to come to your teamspeak's and take a closer look myself.

**Comment by ZeroByter** [comment]
@hadasch1 I _think_ your config is outdated, you should make a backup of it (rename it something else like `config.php.bak`) and make a new one and see if the problem persists.

**Comment by hadasch1** [comment]
Still not working. Same Error

**Comment by hadasch1** [comment]
ZeroByter can you take a look if you can?

**Comment by ZeroByter** [comment]
@hadasch1 Sure! But I need your TeamSpeak IP so I could connect and talk with you.

**Comment by ZeroByter** [comment]
Since this issue has been inactive for 11 days now, I am assuming it has been resolved and I will be closing it.

If you have any further issues or difficulties with the panel, feel free to create a new issue thread!
