### ISSUE TITLE
Obly

### ISSUE THREAD

**Issue by brandxp1** [ZeroByter/zeropanelv2#12]

**Comment by brandxp1** [comment]
Yor Tool dont go, on startup page it load no more...


P.s. Sry for my rly bad english

**Comment by TaktischerSpeck** [comment]
look in your databse if the tool creates databeses and insert in accounts your user

**Comment by brandxp1** [comment]
@TaktischerSpeck ne erstellt keine sachen in der Datenbank

**Comment by TaktischerSpeck** [comment]
ich gucke mal das ich zu dir auf ts komme.

glaube aber das das den mittag nichts wird eher gegen abend oder morgen mittag

**Comment by ZeroByter** [comment]
Since this issue has been inactive for 11 days now, I am assuming it has been resolved and I will be closing it.

If you have any further issues or difficulties with the panel, feel free to create a new issue thread!
