### ISSUE TITLE
Error: Access denied. 

### ISSUE THREAD

**Issue by DZPhoenix** [ZeroByter/zeropanelv2#13]
I've installed your panel and i can reach it under test.deutschland-zockt.net/index.php. But when i try to reach any other page of the panel, I only get this error: "Access denied. ". 
Another Problem is, when i click on dashboard, it redirect me to test.deutschland-zockt.net, but then I only see the standard plesk page.

**Comment by hadasch1** [comment]
Is the panel in a subfolder? If so you have to edit the .htaccess File.

**Comment by DZPhoenix** [comment]
It is only installed on a subdomain. I've made a sreenshot:
![unbenannt](https://user-images.githubusercontent.com/34918261/40548885-470c430c-6036-11e8-8a78-f1e81a37d8e6.PNG)

**Comment by DZPhoenix** [comment]
Okay, i forgot to delete the standard plesk files so... I deleted them and now everything works fine.
