### ISSUE TITLE
Notes doesn't work

### ISSUE THREAD

**Issue by DZPhoenix** [ZeroByter/zeropanelv2#14]
**Describe the bug**
When i add a note. it doesn't show up in the list from the player.

**To Reproduce**
1. Go to 'Players --> Select a player'
2. Click on 'Notes'
3. Write something in the field
4. Click on 'Post'

**Expected behavior**
The panel creates a database entry, but nothing show up in the list. 

**Screenshots**
![1](https://user-images.githubusercontent.com/34918261/43261377-c4084924-90dc-11e8-9967-7d116ba1f4ad.PNG)
![2](https://user-images.githubusercontent.com/34918261/43261382-c6f6357e-90dc-11e8-9e78-9b4b95c301ed.PNG)
![3](https://user-images.githubusercontent.com/34918261/43261383-c92bbf9e-90dc-11e8-97ef-ebc2e86298a8.PNG)

**Were you viewing the panel on desktop or mobile?:**
- Desktop

**Additional context**
---------------------

**Comment by ZeroByter** [comment]
I'm not at my computer at the moment, but I will be available in about 10 minutes.

What's your teamspeak so that we could discuss the bug better?

**Comment by ZeroByter** [comment]
I found the problem and the latest [https://github.com/ZeroByter/zeropanelv2/commit/7f7d09a64d753542ce93b057021bdbe5b1eb873d](patch) should fix the issue

If the issue is still not fixed, please feel free to reach out to me again here on GitHub and I will take a closer look at the problem.
