### ISSUE TITLE
panel very slowly

### ISSUE THREAD

**Issue by SalihCanBinboga** [ZeroByter/zeropanelv2#16]
rom this web panel very slowly what problem :( ?

**Comment by ZeroByter** [comment]
Have you fixed the MySQL tables mismatch?

**Comment by ZeroByter** [comment]
Also, when loading the webpage, press Ctrl + Shift + J and go to the 'Network' tab to see what takes a long time to load.

Also make sure you don't have any VPNs enabled.

**Comment by SalihCanBinboga** [comment]
> Have you fixed the MySQL tables mismatch?

Yes fixed and vpn disable and just not only me all my admins have a problem :(

**Comment by SalihCanBinboga** [comment]
and I looked and check it with ctrl + shift + j all sql querys very slowly but another web panels no problem well mysql fast are you come teamspeak ?

**Comment by ZeroByter** [comment]
I cant come now, but I will come later today at around the same time as
yesterday.

**Comment by SalihCanBinboga** [comment]
wait for you rom

**Comment by SalihCanBinboga** [comment]
last problem: ""[RM]gReTcHen #Mk2#TeQ#BÃ¶  "" player names do not accept Turkish characters @ZeroByter
