### ISSUE TITLE
Create rcon bans log to database table problem

### ISSUE THREAD

**Issue by SalihCanBinboga** [ZeroByter/zeropanelv2#18]
Rcon connect and player bannend no problem but create ban log to bans table problem rom @ZeroByter

**Comment by ZeroByter** [comment]
I will be able to help in about an hour or two. :)

**Comment by SalihCanBinboga** [comment]
@ZeroByter okey rom i waiting for you :+1:

**Comment by SalihCanBinboga** [comment]
@ZeroByter still waiting for you :)

**Comment by ZeroByter** [comment]
@SalihF7 Lol sorry I didnt come earlier, I was busy and I forget... I am here now.

**Comment by SalihCanBinboga** [comment]
@ZeroByter Are u here ? http://prntscr.com/mbrwwl
