### ISSUE TITLE
 Mysql Login Information

### ISSUE THREAD

**Issue by Xbans** [ZeroByter/zeropanelv2#22]
Where would I write my Mysql Login Information, I need to connect my database to which file I can not enter my information.

**Comment by ZeroByter** [comment]
During the initial setup of the panel you are prompted to enter your login credentials.

**Comment by ZeroByter** [comment]
Have you already completed the first time setup for the panel? If not, then
go over the form in the first time setup menu and fill in the database
connection information there.
