### ISSUE TITLE
404 - File or directory not found.

### ISSUE THREAD

**Issue by brandxp1** [ZeroByter/zeropanelv2#24]
If I go to any page, there is a 404 error

Look at the Video:
https://youtu.be/2ZsNQZ2p_XE

At the Log i have this errors:
https://pastebin.com/5vX4JKNh

**Comment by ZeroByter** [comment]
Judging by the logs, I think the problem might be that the webpanel is referring to 'playerid', but your existing database uses 'pid', am I wrong? You can change this easily by going to the settings page and changing the field setting there.

If you can't access the settings page, then no worries, you can also manually edit the config file without use of the website.

If you need any help I would be happy to join you in your Teamspeak and help you solve the problem together.

**Comment by brandxp1** [comment]
On the settings page I do not come ... Now the question is under which path I find the config file?

**Comment by ZeroByter** [comment]
What is your Teamspeak address? Perhaps it would be easier for me to come and help you directly.

**Comment by ZeroByter** [comment]
In any case, the path for the config file is at root of the panel application (meaning where index.php is) and it's called `config.php`. Open that, and look for the setting that you need to change.

**Comment by brandxp1** [comment]
Has now been edited, but still does not work

**Comment by brandxp1** [comment]
The only thing that is different I have no more errors in the logs

**Comment by ZeroByter** [comment]
Do you have Teamspeak? Or AnyDesk? If I can take a look myself I can help fix the issue better.

**Comment by brandxp1** [comment]
AnyDesk ; 723 302 222

**Comment by ZeroByter** [comment]
Your AnyDesk went offline? What happened?

**Comment by brandxp1** [comment]
Sry pls reconect

**Comment by brandxp1** [comment]
Thank you..

**Comment by ZeroByter** [comment]
Issue fixed. For future reference if anyone else also experiences this problem, the issue was caused by IIS not recognizing/supporting .htaccess.

I recommend using XAMPP, since it's what I used to develop ZeroPanel and in my opinion is best suited for PHP.

**Comment by blackfisch** [comment]
Comment on using XAMPP: **Don't**. 

XAMPP is a testing environment and **NOT** suited for production purposes because of security. Yes, there is no .htaccess with IIS but a web.config which is basically the equivalent of a .htaccess - for further reference look here: https://superuser.com/a/800267

I'd just recomment using a linux server for web server hosting, but that's just my opinion :)
For further information why XAMPP is bad, here are some articles: 

- https://lghost.co.uk/2016/09/04/not-use-xampp-production-websites/ 
- https://stackoverflow.com/questions/26297731/why-is-xampp-not-suited-for-production

**Comment by ZeroByter** [comment]
> Comment on using XAMPP: **Don't**.
> 
> XAMPP is a testing environment and **NOT** suited for production purposes because of security. Yes, there is no .htaccess with IIS but a web.config which is basically the equivalent of a .htaccess - for further reference look here: https://superuser.com/a/800267
> 
> I'd just recomment using a linux server for web server hosting, but that's just my opinion :)
> For further information why XAMPP is bad, here are some articles:
> 
> * https://lghost.co.uk/2016/09/04/not-use-xampp-production-websites/
> * https://stackoverflow.com/questions/26297731/why-is-xampp-not-suited-for-production

Oh crap man, I never realized running servers on XAMPP is a bad idea :O, thanks for letting us all know! :+1:
