### ISSUE TITLE
Cannot switch sites

### ISSUE THREAD

**Issue by blackfisch** [ZeroByter/zeropanelv2#25]
See #7 

Hey, it's me again. After a while now I wanted to reinstall your panel and modify it to our needs. only problem, whenever I want to change sites to anything other than the overview page I get a login screen and can't login. I know we fixed the problem last year but don't remember how.

Error Logs show nothing (neither Webserver, PHP or anything else)

The system runs on Debian 8 with an Apache Webserver installed on it.

If you want to talk, he teamspeak adress is ts.mountainvalleyrpg.de - ask for blackfisch

**Comment by ZeroByter** [comment]
I'll be AFK in the Teamspeak in the AFK channel. Come and poke me once you're ready and I'll take a look.

**Comment by blackfisch** [comment]
Sorry, was not here yesterday. It would be nice if you could come today :)

**Comment by ZeroByter** [comment]
I'm here now :)

**Comment by ZeroByter** [comment]
![image](https://user-images.githubusercontent.com/15838111/61375934-bd92d700-a8a8-11e9-8029-81d6cd84acc9.png)

**Comment by ZeroByter** [comment]
Issue fixed, problem was host kept changing IP address which triggered the IP-locking feature (one IP address per session).
