### ISSUE TITLE
Not working ???

### ISSUE THREAD

**Issue by TommyYahan** [ZeroByter/zeropanelv2#4]
Just tried to install the panel on my server and it wont do anything , i input all details of my server onto the setup page but when i click submit it just reloads the page .

**Comment by ZeroByter** [comment]
That's weird. You got Steam or Teamspeak so I could help set it up?

**Comment by TommyYahan** [comment]
yeah sure ,  ill be on at maybe 4pm . ts3.viscositygaming.com
