### ISSUE TITLE
im getting this issue 

### ISSUE THREAD

**Issue by jonathan19022104** [ZeroByter/zeropanelv2#6]
Fatal error: Uncaught Error: Call to undefined function mcrypt_encrypt() in C:\xampp\htdocs\phpscripts\essentials.php:3 Stack trace: #0 C:\xampp\htdocs\phpscripts\requests\dosetup.php(22): encrypt_text('62.210.140.153', '0d8b2c9053f993b...') #1 C:\xampp\htdocs\phpscripts\requests\dosetup.php(39): generateConfigFile() #2 {main} thrown in C:\xampp\htdocs\phpscripts\essentials.php on line 3

**Comment by ZeroByter** [comment]
What version of PHP are you on?

Also, what's your TeamSpeak/Discord? I could come on and help you directly.

**Comment by ZeroByter** [comment]
Nevermind, I figured out why this is happening. mcrypt_encrypt is deprecated in newer versions of PHP, this is now fixed!

**Comment by jonathan19022104** [comment]
im unsure the version of php but i know it use to work only issue we ever had was your ban wasnt working

ts.vertiognetwork.co.uk
www.vertigonetwork.co.uk
________________________________

**Comment by ZeroByter** [comment]
Download the latest version of the panel and it should work. As for the bans I would need to come investigate personally.
