### ISSUE TITLE
Problem with starting

### ISSUE THREAD

**Issue by 1Webix** [ZeroByter/zeropanelv2#9]
Hello

I have problems with your tool, the settings for the tool are not set. the page is only reloaded
sry for my bad Englisch

**Comment by ZeroByter** [comment]
Do you have TeamSpeak? I'll be happy to come help.

**Comment by 1Webix** [comment]
Yes but my Englisch is realy bad. TS: ts.eraze-gaming.de

**Comment by BeFreezy** [comment]
Can confirm, not possible to pass the first-time setup.

**Comment by ZeroByter** [comment]
The web-interface only works with Apache due to it's dependency upon the .htaccess file.

**Comment by BeFreezy** [comment]
I'm currently using apache.

**Comment by ZeroByter** [comment]
Whats your TeamSpeak, BeFreezy?

**Comment by BeFreezy** [comment]
I can't talk right now, what is it we were going to talk about?

**Comment by ZeroByter** [comment]
Are you using the latest version? I think there is a bug with it I am addressing right now.

**Comment by BeFreezy** [comment]
I'll download it and try again, is the current version stable?

**Comment by ZeroByter** [comment]
Don't think so. Give me a few minutes and I'll fix this bug.

**Comment by BeFreezy** [comment]
Alright, hit me up once you're done.

**Comment by ZeroByter** [comment]
Done! Update is live.

Simple typo in `classes/permissions.php` caused all the problems... 😞 

Let me know if anyone has anymore problems?

**Comment by TaktischerSpeck** [comment]
hey you said its need Apache but plesk does run on an Apache webserver so coud you maybe try to help me?

maybe on teamspeak?  ts.thelastgamer.de

if you have the time

**Comment by ZeroByter** [comment]
Can't today, I might be available tomorrow.

**Comment by blackfisch** [comment]
@TaktischerSpeck seems to have the same issues I had @ZeroByter - just try the same things :D

**Comment by TaktischerSpeck** [comment]
@BlackFisch wenn du mir sagen könntest was ihr gemacht habt muss ich nicht die zeit von @ZeroByter  vergeuden

||||||||||||||||||||||||||||||||||||||

@BlackFisch If you could tell me what you did I do not have to waste the time of @ZeroByter

**Comment by blackfisch** [comment]
Zu viel, als dass ich es dir noch genau sagen kann. ich kanns mir aber mal kurz anschauen ob ich was sehe :)

**Comment by ZeroByter** [comment]
If @BeFreezy could give me his TeamSpeak IP, I could hop on and help him.
As for @TaktischerSpeck, are you and @BlackFisch gonna sort this out? Or should I come along?

**Comment by TaktischerSpeck** [comment]
Hey wie tried but it did not Work 

I need you :)

My teamspeak is ts.thelastgamer.de

I also coud come to yours or just Post the error

**Comment by brandxp1** [comment]
Still does not work.......

**Comment by ZeroByter** [comment]
Well gentleman, if there is some bug that occurs for everyone that I could fix once and for all that would be great, but in the mean time it sounds like I have to go to each person's community individually and assist, so it might take a while.

**Comment by ZeroByter** [comment]
Fixed some more bugs I discovered while fixing @TaktischerSpeck's panel. Anyone who has errors should redownload the [newest update](https://github.com/ZeroByter/zeropanelv2/commit/df7c956e9cedbbdb2d876aff9561179de7f70d0c) _again_ and see if it works. If it doesn't and you are shown some sort of an error message, please report it here! (w/ the error message I mean).

**Comment by BeFreezy** [comment]
Still stuck at the first-time setup, no errors no nothing, the page just keeps refreshing.

**Comment by TaktischerSpeck** [comment]
überprüfe mal ob er etwas in die Datenbank einträgt

@ZeroByter Do you have any idear to fix my performance?

**Comment by BeFreezy** [comment]
Nope, trägt nichts ein.

@TaktischerSpeck

**Comment by TaktischerSpeck** [comment]
Hm

@ZeroByter he has the same insert Problem like me

**Comment by ZeroByter** [comment]
@BeFreezy Are you hosting the panel from a sub-directory of a website (www.forums.com/panel) or from a sub-domain (www.panel.forums.com)?

If the former, then the panel will not work because it's trying to access resources that are not where it thinks they are.

**Comment by ZeroByter** [comment]
@TaktischerSpeck Not really, it's something to do with your server or perhaps the domain service?

**Comment by TaktischerSpeck** [comment]
Hm gonna Check on it later but my Server does not Show any usage

**Comment by ZeroByter** [comment]
@TaktischerSpeck Maybe the domain doesn't have any caching? That could be bad.

**Comment by TaktischerSpeck** [comment]
Actually i dont know

How coud i Check?

**Comment by ZeroByter** [comment]
Come on ts, I'll help.

**Comment by TaktischerSpeck** [comment]
I am at school ATM

I will be there later gonna write here

**Comment by ZeroByter** [comment]
Since this issue has been inactive for 13 days now, I am assuming it has been resolved and I will be closing it.

If you have any further issues or difficulties with the panel, feel free to create a new issue thread!
